### ISSUE TITLE
If I only have one GPU, how to set the config.py?

### ISSUE THREAD

**Issue by zhixuanli** [ycszen/TorchSeg#11]
Thanks for your great project, it's really helpful.

I only have one GPU, when I try to run the `train.py` of the cityscapes.bisenet.R18, the following error occured:

> Traceback (most recent call last):
  File "/home/oliver/PycharmProjects/TorchSeg/model/bisenet/cityscapes.bisenet.R18/train.py", line 131, in <module>
    loss = model(imgs, gts)
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/TorchSeg/model/bisenet/cityscapes.bisenet.R18/network.py", line 77, in forward
    spatial_out = self.spatial_path(data)
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/TorchSeg/model/bisenet/cityscapes.bisenet.R18/network.py", line 133, in forward
    x = self.conv_7x7(x)
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/TorchSeg/furnace/seg_opr/seg_oprs.py", line 32, in forward
    x = self.bn(x)
  File "/home/oliver/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/TorchSeg/furnace/seg_opr/sync_bn/syncbn.py", line 50, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

After reading this [page](https://github.com/zhanghang1989/PyTorch-Encoding/issues/75), I'm wondering how to run this code on the single GPU.

Can you give me some tips? Thank you so much!!

**Comment by zhixuanli** [comment]
According to this page: [https://github.com/zhanghang1989/PyTorch-Encoding/issues/148](https://github.com/zhanghang1989/PyTorch-Encoding/issues/148)

Do I really have to change the BatchNorms code manually for each position?

Is there some easier approach? :smile:

**Comment by XdpAreKid** [comment]
I meet the same error,how did you fix that? @zhixuanli

**Comment by zhixuanli** [comment]
@XdpAreKid I changed each postion to standard BatchNorms by hand.

Here's the code :[https://github.com/zhixuanli/semantic-segmentation-pytorch](https://github.com/zhixuanli/semantic-segmentation-pytorch)

Thanks to @ycszen

**Comment by ycszen** [comment]
> @XdpAreKid I changed each position to standard BatchNorms by hand.
> 
> Here's the code: https://github.com/zhixuanli/semantic-segmentation-pytorch
> 
> Thanks to @ycszen

@zhixuanli  You can fork from my repo and then change, instead of copying directly.

**Comment by XdpAreKid** [comment]
@zhixuanli 谢谢你的代码，我已经解决了。但是我还遇到了一些问题，应该和我的数据有问题，我再想想怎么解决吧。 @ycszen 他那样改可能没有普适性，只是在train.py里把BatchNorm2d换成torch.nn里的，再将loss的计算那里，手动平均一下

**Comment by zhixuanli** [comment]
@ycszen 
Copying but not forking, is for blending many codes from different repos. 

Thank you so much!!

**Comment by liuxy416** [comment]
@ycszen @zhixuanli @XdpAreKid Still have problems on training on single gpu, could you please share the steps of training?

**Comment by zhixuanli** [comment]
@liuxy416 
```
from config import config
from dataloader import get_train_loader
from network import BiSeNet
from datasets import Cityscapes
from utils.init_func import init_weight, group_weight
from engine.lr_policy import PolyLR
from engine.engine import Engine
from seg_opr.loss_opr import SigmoidFocalLoss, ProbOhemCrossEntropy2d
from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d

BatchNorm2d = torch.nn.BatchNorm2d
engine.distributed = False
```

Just add the last two lines:
```
BatchNorm2d = torch.nn.BatchNorm2d
engine.distributed = False
```

If not ok, delete this line (maybe line 107):
```
        model = DataParallelModel(model, device_ids=engine.devices)
```

**Comment by liuxy416** [comment]
> @liuxy416
> 
> ```
> from config import config
> from dataloader import get_train_loader
> from network import BiSeNet
> from datasets import Cityscapes
> from utils.init_func import init_weight, group_weight
> from engine.lr_policy import PolyLR
> from engine.engine import Engine
> from seg_opr.loss_opr import SigmoidFocalLoss, ProbOhemCrossEntropy2d
> from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d
> 
> BatchNorm2d = torch.nn.BatchNorm2d
> engine.distributed = False
> ```
> Just add the last two lines:
> 
> ```
> BatchNorm2d = torch.nn.BatchNorm2d
> engine.distributed = False
> ```
> If not ok, delete this line (maybe line 107):
> 
> ```
>         model = DataParallelModel(model, device_ids=engine.devices)
> ```

Thank you for your reply! I change the code just like you said, but i still get a error when calculating loss:
`loss = Reduce.apply(*loss) / len(loss)`

the trace is:
`File "train.py", line 140, in <module>
    loss = Reduce.apply(*loss) / len(loss)
  File "/xxx/site-packages/torch/tensor.py", line 422, in __iter__
    raise TypeError('iteration over a 0-d tensor')`

Do you have any solutions?
Thanks again.

**Comment by zhixuanli** [comment]
@liuxy416 
Just delete this line

**Comment by yaodonggggggg** [comment]
> @liuxy416
> 
> ```
> from config import config
> from dataloader import get_train_loader
> from network import BiSeNet
> from datasets import Cityscapes
> from utils.init_func import init_weight, group_weight
> from engine.lr_policy import PolyLR
> from engine.engine import Engine
> from seg_opr.loss_opr import SigmoidFocalLoss, ProbOhemCrossEntropy2d
> from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d
> 
> BatchNorm2d = torch.nn.BatchNorm2d
> engine.distributed = False
> ```
> Just add the last two lines:
> 
> ```
> BatchNorm2d = torch.nn.BatchNorm2d
> engine.distributed = False
> ```
> If not ok, delete this line (maybe line 107):
> 
> ```
>         model = DataParallelModel(model, device_ids=engine.devices)
> ```

I just have one gpu too,I change the code like you said,but I have other errors

> 29 20:50:05 PyTorch Version 1.0.1.post2, Furnace Version 0.1.1
[00:00<?,?it/s]Traceback (most recent call last):
  File "/home/faustino/python_workshop/TorchSeg-master/model/dfn/voc.dfn.R101_v1c/train.py", line 120, in <module>
    loss = model(imgs, gts, cgts)
  File "/home/faustino/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faustino/python_workshop/TorchSeg-master/model/dfn/voc.dfn.R101_v1c/network.py", line 145, in forward
    aux_loss0 = self.aux_criterion(boder_out[0], aux_label)
  File "/home/faustino/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faustino/python_workshop/TorchSeg-master/furnace/seg_opr/loss_opr.py", line 33, in forward
    pos_part = (1 - pred_sigmoid) ** self.gamma * (
  File "/home/faustino/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 363, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: CUDA error: device-side assert triggered

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/faustino/backup/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/faustino/backup/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/faustino/backup/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/faustino/backup/pycharm-community-2018.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/faustino/python_workshop/TorchSeg-master/model/dfn/voc.dfn.R101_v1c/train.py", line 154, in <module>
    config.log_dir_link)
  File "/home/faustino/python_workshop/TorchSeg-master/furnace/engine/engine.py", line 154, in __exit__
    torch.cuda.empty_cache()
  File "/home/faustino/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 374, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
/opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [2,0,0], thread: [480,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1549630534704/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [2,0,0], thread: [481,0,0] Assertion `t >= 0 && t < n_classes` failed.
We've got an error while stopping in post-mortem: <class 'KeyboardInterrupt'>

Please give me a hand.
