### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.pyt_utils'

### ISSUE THREAD

**Issue by artzimy** [ycszen/TorchSeg#118]
Trying to run bash script.sh I got the following error

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from dataloader import get_train_loader
  File "/media/D/users/Idan/Suha_Maryam/TorchSemiSeg-main/exp.voc/voc8.res50v3+.CPS/dataloader.py", line 8, in <module>
    from utils.img_utils import generate_random_crop_pos, random_crop_pad_to_shape
ModuleNotFoundError: No module named 'utils.img_utils'
Traceback (most recent call last):
  File "eval.py", line 13, in <module>
    from utils.pyt_utils import ensure_dir, link_file, load_model, parse_devices
ModuleNotFoundError: No module named 'utils.pyt_utils' 

Adding [to script.sh before import utils]
PYTHONPATH="<MyPath>/TorchSemiSeg-main/furnace/"  
Did not solve the problem

What could be the problem?
Thanks
Moran

**Comment by Lingxuewang** [comment]
You could try this:
import sys
sys.path.append('absolute path of you  file: img_utils')

**Comment by ChenShupan** [comment]
I also encountered this problem when running the program. I tried your method and it didn't solve it. What is the specific reason? Is there a way to solve it?

**Comment by ChenShupan** [comment]
> 你可以试试这个：导入sys sys.path.append（'你的文件的绝对路径：img_utils'）

I also encountered this problem when running the program. I tried your method and it didn't solve it. What is the specific reason? Is there a way to solve it?
