### ISSUE TITLE
Problem with Sync_BN and CUDA

### ISSUE THREAD

**Issue by sanshibayuan** [ycszen/TorchSeg#14]
This is what I got from running the code
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d
  File "/Data/TorchSeg/furnace/seg_opr/sync_bn/__init__.py", line 8, in <module>
    from .syncbn import *
  File "/Data/TorchSeg/furnace/seg_opr/sync_bn/syncbn.py", line 17, in <module>
    from .functions import *
  File "/Data/TorchSeg/furnace/seg_opr/sync_bn/functions.py", line 13, in <module>
    from .src import *
  File "/Data/TorchSeg/furnace/seg_opr/sync_bn/src/__init__.py", line 18, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'syncbn_gpu': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=syncbn_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/torch/csrc/api/include -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/TH -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.5m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /Data/TorchSeg/furnace/seg_opr/sync_bn/src/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
FAILED: syncbn_kernel.cuda.o
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=syncbn_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/torch/csrc/api/include -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/TH -isystem /usr/local/lib/python3.5/dist-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.5m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /Data/TorchSeg/furnace/seg_opr/sync_bn/src/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
In file included from /Data/TorchSeg/furnace/seg_opr/sync_bn/src/gpu/syncbn_kernel.cu:4:0:
/usr/local/lib/python3.5/dist-packages/torch/lib/include/ATen/cuda/CUDAContext.h:12:22: fatal error: cusparse.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.


```

I looked everywhere and found out that it was CUDA that caused the problem. It seems to be associate with the `CUDAContext.h `file, it can not found any of the header files, e.g. `cusparse.h`, `cublas_v2.h`... 

I don't know how to solve it 
I've tried reintalling pytorch from source but no use.
Can someone help me, MUCH THANKS!

**Comment by SwagJ** [comment]
Hi, 

Could you post your solution? Thank you very much!
