### ISSUE TITLE
Where can i download the ResNet18 pretrained model??

### ISSUE THREAD

**Issue by XdpAreKid** [ycszen/TorchSeg#15]
Hello, I can't the way to download the pretrained model of resnet18 which is converted from gluon

**Comment by zhixuanli** [comment]
In which code that needs the pretrained model of resnet18? @XdpAreKid

**Comment by ycszen** [comment]
@XdpAreKid I will release the pre-trained model recently.

**Comment by luke-evans-liu** [comment]
> @XdpAreKid I will release the pre-trained model recently.

Please quickly.

**Comment by XdpAreKid** [comment]
@luke-evans-liu I use [this](https://github.com/zhanghang1989/gluoncv-torch).It can get a good result  in my data

**Comment by moonmyth** [comment]
@XdpAreKid i use gluon
it makes the mistake like this:
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    norm_layer=BatchNorm2d)
  File "/TorchSeg/model/bisenet/cityscapes.bisenet.R18/network.py", line 26, in __init__
    deep_stem=False, stem_width=64)
  File "/TorchSeg/furnace/base_model/resnet.py", line 191, in resnet18
    model = load_model(model, pretrained_model)
  File "/TorchSeg/furnace/utils/pyt_utils.py", line 41, in load_model
    model.load_state_dict(state_dict, strict=False)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 742, in load_state_dict
    state_dict = state_dict.copy()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'ResNet' object has no attribute 'copy'

**Comment by XdpAreKid** [comment]
How did you load the model? @moonmyth

**Comment by moonmyth** [comment]
load model as follow in config.py
C.pretrained_model = gcv.models.resnet18(pretrained=True)

**Comment by alexanderfrey** [comment]
Any updates on how to load a pretrained model ?

**Comment by XdpAreKid** [comment]
@moonmyth @alexanderfrey For my code, i just down [this weights](https://github.com/zhanghang1989/gluoncv-torch) in my computer, and then in config.py 
C.pretrained_model = 'path to your weights'

**Comment by majuncai** [comment]
> load model as follow in config.py
> C.pretrained_model = gcv.models.resnet18(pretrained=True)

I have the same problem . have you solved it
