### ISSUE TITLE
Where should I run train.py?

### ISSUE THREAD

**Issue by hubutui** [ycszen/TorchSeg#19]
Should I enter `model/bisenet/cityscapes.bisenet.R18` and run `train.py` or just in the top of root dir? I got error:
```text
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from config import config
  File "/home/USER/Projects/TorchSeg-BiSeNet/model/bisenet/cityscapes.bisenet.R18/config.py", line 56, in <module>
    from utils.pyt_utils import model_urls
ModuleNotFoundError: No module named 'utils'
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from config import config
  File "/home/USER/Projects/TorchSeg-BiSeNet/model/bisenet/cityscapes.bisenet.R18/config.py", line 56, in <module>
    from utils.pyt_utils import model_urls
ModuleNotFoundError: No module named 'utils'
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from config import config
  File "/home/USER/Projects/TorchSeg-BiSeNet/model/bisenet/cityscapes.bisenet.R18/config.py", line 56, in <module>
    from utils.pyt_utils import model_urls
ModuleNotFoundError: No module named 'utils'
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from config import config
  File "/home/USER/Projects/TorchSeg-BiSeNet/model/bisenet/cityscapes.bisenet.R18/config.py", line 56, in <module>
    from utils.pyt_utils import model_urls
ModuleNotFoundError: No module named 'utils'
```
I found that `furnace/utils`, maybe wrong dir?

**Comment by ms-krajesh** [comment]
@hubutui : You should run train.py inside "model/bisenet/cityscapes.bisenet.R18" directory.

**Comment by hubutui** [comment]
Ok, I fix it by adding
```shell
sys.path.append('/home/USER/Projects/TorchSeg-BiSeNet/furnace')
```
to `train.py` before import utils.
