### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hubutui** [ycszen/TorchSeg#20]
I wanna know why and is `imp.py` loading cause an error about `libcudart.so.9.0`. I have cuda 10 installed in my conda environment, not cuda 9.
```text
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d
  File "/home/USER/Projects/TorchSeg-BiSeNet/furnace/seg_opr/sync_bn/__init__.py", line 8, in <module>
    from .syncbn import *
  File "/home/USER/Projects/TorchSeg-BiSeNet/furnace/seg_opr/sync_bn/syncbn.py", line 17, in <module>
    from .functions import *
  File "/home/USER/Projects/TorchSeg-BiSeNet/furnace/seg_opr/sync_bn/functions.py", line 13, in <module>
    from .src import *
  File "/home/USER/Projects/TorchSeg-BiSeNet/furnace/seg_opr/sync_bn/src/__init__.py", line 18, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/home/USER/.conda/envs/BiSeNet-official-test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/USER/.conda/envs/BiSeNet-official-test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/USER/.conda/envs/BiSeNet-official-test/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 968, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/USER/.conda/envs/BiSeNet-official-test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/USER/.conda/envs/BiSeNet-official-test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
```
Complete log is in attach: [log.txt](https://github.com/ycszen/TorchSeg/files/2900964/log.txt)

**Comment by ms-krajesh** [comment]
@hubutui: The issue seems to be related to the faulty CuDNN installation. For this Install CUDA 10.0 and then install corresponding CuDNN version (	https://developer.nvidia.com/rdp/cudnn-download) for CUDA 10.0. Then verify cUDNN installation using steps mentioned here: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html.  

CuDNN verification might fail, so see the solution here: https://devtalk.nvidia.com/default/topic/1025801/cudnn/cudnn-test-did-not-pass/

If you are planning to use multi gpu training then can also install Apex after CUDA and CuDNN installation. Update your environment variables accordingly. Apex installation has some run time issues with CUDA 9.0 and 9.2.

**Comment by hubutui** [comment]
Thanks. It seems that when compiling apex, we need nvcc, which is not provided by conda. Also, pytorch find cuda by `CUDA_HOME` environment variable, the default is usually `/usr/local/cuda`. In my system, `/usr/local/cuda` points to `/usr/local/cuda-9.0`. Therefore, I compiled apex with cuda 9.0, but run it with cuda 10. I'm not sure there's a way to compile pytorch cpp extensions in conda environment.

**Comment by ms-krajesh** [comment]
@hubutui: Yes you are right. I have compiled successfully Apex with cpp extensions in Anaconda environment. I have used following command: python setup.py install --cuda_ext --cpp_ext
Note: I have used CUDA 10.0 for Apex compilation
