### ISSUE TITLE
The expanded size of the tensor (256000) must match the existing size (253924) at non-singleton dimension 1.  Target sizes: [2, 256000].  Tensor sizes: [253924]

### ISSUE THREAD

**Issue by umiiwa** [ycszen/TorchSeg#40]
The shape of my images is:
C.image_height = 1596
C.image_width = 2552

I set 
C.target_size = 1024
C.base_size = 832

Is the question below related to my config?

Question:
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    loss = model(imgs, gts)
  File "/home/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/yhy/TorchSeg/model/bisenet/license_plate.bisenet.X39.speed/network.py", line 107, in forward
    aux_loss0 = self.ohem_criterion(self.heads[0](pred_out[0]), label)
  File "/home/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/yhy/TorchSeg/furnace/seg_opr/loss_opr.py", line 79, in forward
    prob = prob.masked_fill_(1 - valid_mask, 1)
RuntimeError: The expanded size of the tensor (256000) must match the existing size (253924) at non-singleton dimension 1.  Target sizes: [2, 256000].  Tensor sizes: [253924]

**Comment by ms-krajesh** [comment]
image dimension should be multiple of power of 2.

**Comment by umiiwa** [comment]
> image dimension should be multiple of power of 2.

Thanks for your reply! I've solved this problem by using the image dimension (1024,1024) in the original config instead of my image dimension.

**Comment by umiiwa** [comment]
> > image dimension should be multiple of power of 2.
> 
> Thanks for your reply! I've solved this problem by using the image dimension (1024,1024) in the original config instead of my image dimension.
