### ISSUE TITLE
Batch normalization function missed

### ISSUE THREAD

**Issue by Nyquist0** [ycszen/TorchSeg#46]
Hi Dr.Yu,
Your source code is very very valuable.
I found in latest version of your suit, you deleted your _sync_bn_  package. 
And in the _BiSeNet_ training code, you deleted ` from seg_opr.sync_bn import BatchNorm2d.` Thus it means to use _sync_bn2d_ in the package APEX?

But the error occured as following.
`Traceback (most recent call last):
  File "/home/cgv841/litao/TorchSeg/model/bisenet/cityscapes.bisenet.R18/train.py", line 128, in <module>
    loss = model(imgs, gts)
  File "/home/cgv841/anaconda3/envs/segpt1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cgv841/litao/TorchSeg/model/bisenet/cityscapes.bisenet.R18/network.py", line 104, in forward
    aux_loss0 = self.criterion(self.heads[0](pred_out[0]), label)
  File "/home/cgv841/anaconda3/envs/segpt1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cgv841/litao/TorchSeg/furnace/seg_opr/loss_opr.py", line 84, in forward
    index = mask_prob.argsort()
  File "/home/cgv841/anaconda3/envs/segpt1.0/lib/python3.6/site-packages/torch/tensor.py", line 248, in argsort
    return torch.argsort(self, dim, descending)
  File "/home/cgv841/anaconda3/envs/segpt1.0/lib/python3.6/site-packages/torch/functional.py", line 651, in argsort
    return torch.sort(input, -1, descending)[1]
RuntimeError: merge_sort: failed to synchronize: device-side assert triggered`

I use 2 GPUs of 1080Ti, and batch-size=8

**Comment by ycszen** [comment]
Yes. In the lates version, we use the sync bn of apex.

**Comment by ycszen** [comment]
The label value is not in the range of the 0-19, which results in this error.
In our experiments, we use the transformed dataset. Therefore, you may need to transform the ground truth first.
