### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.stuff10k'

### ISSUE THREAD

**Issue by sounansu** [ycszen/TorchSeg#48]
Hi.
I download `cityscapes-bisenet-R18-speed.pth` and set to `orchSeg/model/bisenet/` directory.
And 

```
$ python eval.py
Traceback (most recent call last):
  File "eval.py", line 18, in <module>
    from datasets.cityscapes import Cityscapes
  File "/home/sounansu/anaconda3/TorchSeg/furnace/datasets/__init__.py", line 5, in <module>
    from .stuff10k import Stuff10K
ModuleNotFoundError: No module named 'datasets.stuff10k'
```

Where is .stuff10k ?

**Comment by mengzhibin** [comment]
If you dont need stuff10k, just removing the lines from the __init__.py will be ok

**Comment by ycszen** [comment]
I have deleted it. Thanks for pointing it out.
