### ISSUE TITLE
i have a question about train？

### ISSUE THREAD

**Issue by E18301194** [ycszen/TorchSeg#96]
(Seg)
maran@cvpruser:/DATA/maran/anaconda3/Project/TorchSeg/model/psanet/ade.psanet.R50_v1c$ python train.py
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from network import PSPNet
  File "/DATA/maran/anaconda3/Project/TorchSeg/model/psanet/ade.psanet.R50_v1c/network.py", line 10, in <module>
    from base_model import resnet50
  File "/DATA/maran/anaconda3/Project/TorchSeg/furnace/base_model/__init__.py", line 3, in <module>
    from .xsnet import XSNet, xsnet16, xsnet18, xsnet18v2, xsnet1x18, xsnet23, \
ModuleNotFoundError: No module named 'base_model.xsnet'
 thx for you code，  i have aquestion about train.  i take 'python train.py' on '/model/psanet/ade.psanet.R50_v1c'. i
 don't know how solve this  question.I can't find 'xsnet' .Can you help my?

**Comment by ycszen** [comment]
Thanks for pointing it out.
I have solved this problem.
